#!/usr/bin/env python3
"""Aggregate k6 JSON summaries into a deterministic markdown table."""
import json
from pathlib import Path
from datetime import datetime, timezone

RESULTS = Path(__file__).parent / "results"
SCRIPTS = ["auth-flow", "proposals-flow", "requests-flow", "proposals-create-flow"]
PROFILES = ["smoke", "load", "stress"]


def ms(value):
    return f"{value:.0f}" if value is not None else "—"


def pct(value):
    return f"{value * 100:.2f}%" if value is not None else "—"


def values(metric: dict):
    # k6 <2 nests stats under "values"; k6 >=2 exposes them directly on the metric.
    return metric.get("values", metric)


def extract(path: Path):
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    metrics = data.get("metrics", {})
    duration = values(metrics.get("http_req_duration", {}))
    failed = values(metrics.get("http_req_failed", {}))
    rps = values(metrics.get("http_reqs", {}))
    return {
        "p50": duration.get("med"),
        "p95": duration.get("p(95)"),
        "p99": duration.get("p(99)"),
        "rps": rps.get("rate"),
        # k6 >=2 reports the failed ratio as "value"; older versions used "rate".
        "err": failed.get("value", failed.get("rate")),
    }


def main():
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    print(f"# k6 Load Test Results ({now})\n")
    print("Generated by `tests/k6/generate-report.py`.\n")
    print("| Endpoint | Profile | p50 (ms) | p95 (ms) | p99 (ms) | req/s | err % |")
    print("|---|---|---:|---:|---:|---:|---:|")

    for script in SCRIPTS:
        for profile in PROFILES:
            row = extract(RESULTS / f"summary-{script}-{profile}.json")
            if row is None:
                print(f"| {script} | {profile} | — | — | — | — | — |")
                continue
            print(
                f"| {script} | {profile} | {ms(row['p50'])} | {ms(row['p95'])} "
                f"| {ms(row['p99'])} | {row['rps']:.2f} | {pct(row['err'])} |"
            )

    print("\n## Analysis\n")
    print("_Fill in narrative observations: SLA holds? saturation point? recommendations?_\n")


if __name__ == "__main__":
    main()
