sonar.projectKey=ratzPereira_AgroConnect
sonar.organization=ratzpereira
sonar.projectName=AgroConnect

# Sources
sonar.sources=backend/src/main/java,frontend/src

# Tests
sonar.tests=backend/src/test/java,frontend/src
sonar.test.inclusions=**/*Test.java,**/*IT.java,**/*.test.ts,**/*.test.tsx

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/migration/**

# Java coverage
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

# TypeScript/JavaScript coverage
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info
